### ISSUE TITLE
관리자의 회원 정보 수정 API

### ISSUE THREAD

**Issue by ohinhyuk** [HGU-WALAB/histudy-be#115]
## Description

현재 회원 정보 수정 API는 ( /api/admin/edit-user ) 하나로만 이루어지고 있다.
이 API는 관리자 페이지에서 매칭 , 비매칭 회원에 대해서 이루어 진다.

API가 Team number를 요구 한다.
하지만 Team number를 보내지 않으면 회원 정보가 수정되지 않는다.

그래서 팀매칭이 이루어지지 않았을 때 회원정보를 매니저쪽에서 수정이 불가능하다.

## 해결 방법

1) 팀 매칭이 이루어 졌을 때만 회원 정보 수정이 가능하도록 한다.
2) 팀 매칭이 이루어 지지 않더라도 회원 정보 수정이 가능하도록 Team number를 nullable 하게 한다.

**Comment by zionhann** [comment]
팀 배정이 되지 않은 유저에 대해서도 회원정보 수정이 가능하게 하자는 말씀이죠?
역으로 팀배정된 학생을 배정 취소시킬수도 있겠군요
