### ISSUE TITLE
Request : 수정 사항을 위한 Front -> Back 요청 사항

### ISSUE THREAD

**Issue by ohinhyuk** [HGU-WALAB/histudy-be#141]
## Description

교수님의 요청 사항에 맞게 수정 하려면 아래에 해당하는 부분을 백엔드에서 추가 작업이 필요하다.

## 요청사항
(1) 신청자 목록에, 학생들 이메일 주소가 나오면 좋겠어요 스터디 하는 학생들에게 일괄 메일 보낼 때 필요합니다.

-> 
`/api/admin/manageGroup`
`/api/admin/unmatched-users`
`/api/admin/allUsers`
`/api/admin/users/unassigned`

네 가지 api에서 학생들의 정보를 보내 줄 때 학생의 이메일을 추가해줘서 보내줘야 한다.

(2) 학생들이 자신의 그룹 번호를 모르는 것 같습니다. 아래 스터디 그룹 정보 타이틀에 그룹 번호가 나오면 좋겠어요.
그룹 번호를 학생들이 알아야, 나중에 그룹 조정하고 할 때 편합니다.

`/api/team/users`
위 api에서 팀원들의 정보들을 보내주는데 자신의 그룹 번호도 함께 보내줘야 합니다.
모든 팀원 마다 보내줄 필요 없이 자신의 그룹 번호 하나만 추가해 보내주시면 됩니다.

**Comment by zionhann** [comment]
확인했습니다.
