### ISSUE TITLE
Request : 이미지 저장 500 Server Error

### ISSUE THREAD

**Issue by ohinhyuk** [HGU-WALAB/histudy-be#142]
## Error Description

```
resource:
  path: http://localhost:8080
  location: img
```
로 JPG 파일을 전달하였을 때 img 폴더는 생성 되나 이미지가 들어가지 않고 500 에러가 터집니다.

![스크린샷 2023-10-23 오전 5 13 57](https://github.com/HGU-WALAB/histudy-be/assets/49269218/36e49e0d-a22f-4ab1-89e7-4cb8124e7d6e)

## 요청 사항

1. application.yml 에 추가 해야 하는 내용 ( custom.resource.path , custom.resource.location 등 )
2. 이미지 압축 여부 ( 백에서 진행 했는 지 ..? or 프론트에서 압축해서 보내줘야 하는 지 )
3. api url에 있는 reportIdOr의 뜻 ( 수정 일 때는 reportId를 보낼 수 있으나 생성 일 때는 reportId가 없다)
4. 에러의 이유

**Comment by zionhann** [comment]
> application.yml 에 추가 해야 하는 내용 ( custom.resource.path , custom.resource.location 등 )

일단 값이 잘못된 것 같은데 따로 전달하겠습니다.

> 이미지 압축 여부 ( 백에서 진행 했는 지 ..? or 프론트에서 압축해서 보내줘야 하는 지 )

압축 과정은 필요하고, 기존에 했던대로 프론트에서 압축해서 보내주면 됩니다.

> api url에 있는 reportIdOr의 뜻 ( 수정 일 때는 reportId를 보낼 수 있으나 생성 일 때는 reportId가 없다)

말씀하신대로 이미지를 먼저 업로드하고 보고서를 생성하기 때문에 생성 과정에는 `reportId`가 없습니다.
생성할때는 `POST /reports/image`, 수정할 때는 `POST /reports/{reportId}/image` 로 보내주시면 됩니다.

`reportIdOr` nullable 한 보고서 번호를 의미합니다. 보고서 번호가 주어지고 해당 보고서에 연결된 이미지 중 업로드하려는 이미지와 같은 이미지가 있는 경우, 이미지를 새로 저장하지 않고 해당 이미지를 응답하게 됩니다.

> 에러의 이유

`resource.path` 와 `resource.location` 값이 잘못되었습니다.
