### ISSUE TITLE
Git Commit Convention

### ISSUE THREAD

**Issue by zionhann** [HGU-WALAB/histudy-be#6]
## 요약
- 양식: `{타입}: {메시지} (#{이슈번호})`

## 예시
```
Feat: 스터디 보고서 작성 (#123)
```

## 주요 타입
name | description
-- | --
Feat | 새로운 기능
Fix | 버그 수정
Rename | 파일, 변수 이름 변경
Refactor | 코드 리팩토링
Test | 테스트 코드 작성

**Comment by ohinhyuk** [comment]
퍼가요~
