### ISSUE TITLE
Branching Model

### ISSUE THREAD

**Issue by zionhann** [HGU-WALAB/histudy-be#7]
## 요약
- [깃허브 플로우](https://docs.github.com/en/get-started/quickstart/github-flow)를 사용해 브랜칭 모델을 구성한다.

## 워크플로우
0. 이슈 생성: 커밋할 변경 사항에 대해 이슈 생성
1. 브랜치 생성:  `main` 브랜치에서 브랜치 컨벤션에 따라 분기
2. 커밋: #6  에 맞게 커밋 메시지 작성
3. 풀 리퀘스트(PR): `main` 브랜치로 병합 요청 
4. 코드 리뷰후 1인 이상 승인
5. `main` 브랜치 병합

## 브랜치 컨벤션
- 양식
```
{도메인}/#{이슈번호}
```
- 도메인 예시: `report`, `auth`, `group`, ...

**Comment by ohinhyuk** [comment]
퍼가요~
